import type { Metadata } from "next";

import { ModeToggle } from "@/components/modeToggle";
import { SmoothCursorWrapper } from "@/components/ui/SmoothCursorWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Header from "@/components/layouts/Header";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <SmoothCursorWrapper />

      <main className="">
        <Header />
        {children}
        <div className="fixed bottom-4 right-4 z-[1002]">
          <ModeToggle />
        </div>
      </main>
    </>
  );
}
