import type { Metadata } from "next";

// import { ModeToggle } from "@/components/modeToggle";
import { ScrollProvider } from "@/components/scrollProvider";
import { ThemeProvider } from "@/components/themeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import { SmoothCursorWrapper } from "@/components/ui/SmoothCursorWrapper";
import { getFooterContent } from "@/lib/api";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch footer content
  let footerContent = null;
  try {
    footerContent = await getFooterContent();
  } catch (error) {
    console.error("Error fetching footer content:", error);
  }
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="light"
      // enableSystem
      disableTransitionOnChange
      storageKey="theme"
    >
      <ScrollProvider>
        <SmoothCursorWrapper />

        <main className="">
          <Header />
          {children}
          {/* <div className="fixed bottom-4 right-4 z-[1002]">
            <ModeToggle />
          </div> */}
          <Footer footerContent={footerContent || undefined} />
        </main>
      </ScrollProvider>
    </ThemeProvider>
  );
}
