import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/themeProvider";
import { ScrollProvider } from "@/components/scrollProvider";
import { SmoothCursor } from "@/components/ui/smooth-cursor";
import { ModeToggle } from "@/components/modeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Figtree } from 'next/font/google';
import Header from "@/components/layouts/Header";

const figtree = Figtree({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-figtree',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${figtree.variable} antialiased`}
        data-scroll-container
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          storageKey="theme"
        >
          <ScrollProvider>
          <SmoothCursor />

            <main className="">
            <Header/>
            {children}
            </main>
          </ScrollProvider>
        </ThemeProvider>
        <div className="fixed bottom-4 right-4 z-[1002]">
          <ModeToggle />
        </div>
      </body>
    </html>
  );
}
